[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0"
]
unused-allowed-license = "warn"

[bans]
multiple-versions = "warn"
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
