[package]
name = "blocks-cs-search"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror = "1.0"
rayon = "1.8"
num-traits = "0.2"
